### ISSUE TITLE
Error running angular-pdfjs

### ISSUE THREAD

**Issue by DevQueen** [ArchmageInc/angular-pdfjs#10]
I receive the error:

0x800a138f - JavaScript runtime error: Unable to get property 'errors' of undefined or null reference

on this line:

`PDFJS.verbosity = PDFJS.VERBOSITY_LEVELS.errors;
`

**Comment by ArchmageInc** [comment]
What version of PDFJS are you using?

**Comment by DevQueen** [comment]
The latest version.  I believe it is 1.4

**Comment by danielmhair** [comment]
I am getting an error about `PDFJS.verbosity = PDFJS.VERBOSITY_LEVELS.errors;` as well. I was unable to `bower install` because it had an angular conflict (Not sure why, I use Angular 1.5.5). Any tips can help. @DevQueen were you able to fix this error? @ArchmageInc any ideas?

**Comment by danielmhair** [comment]
Actually, I fixed it. I was able to fix this error by taking the files from `example/js/lib/pdf.worker.js` and `example/js/lib/pdf.js`.

These are the scripts I added to my `index.html` file, if anyone wanted to know.

```
  <script type="text/javascript" src="lib/angular-pdfjs/example/js/lib/pdf.js"></script>
  <script type="text/javascript" src="lib/angular-pdfjs/example/js/lib/pdf.worker.js"></script>
  <script type="text/javascript" src="lib/angular-pdfjs/dist/angular-pdfjs.min.js" ></script>
```
